# Pan-Tilt Control System Configuration

# Server settings (for the API server to listen on)
server:
  host: 127.0.0.1   # Listen on loopback interface only (local connections only)
  port: 5000        # Default API server port

# Client settings (for the GUI to connect to)
client:
  host: localhost   # Local connection address (127.0.0.1 would also work)
  port: 5000        # Should match server port

# Device configuration
device:
  type: simulator   # 'real' for hardware, 'simulator' for virtual device
  port: COM3        # Serial port for real device (ignored by simulator)
  baudrate: 9600    # Serial baudrate (ignored by simulator)
  address: 1        # Device address (1-255)
  blocking: false   # Whether to wait for movements to complete
  timeout: 1.0      # Serial timeout in seconds (ignored by simulator)

# Safety settings
safety:
  limit_degrees: 45.0      # Maximum movement from home position
  warning_threshold: 0.85  # Threshold for warning indicator (0.0-1.0)
  timeout_seconds: 5.0     # Automatic stop after continuous movement
