connection:
  port: COM3            # Use simulator instead of COM port
  baudrate: 9600
  timeout: 1.0
  retries: 3                 
  retry_delay: 0.5
  polling_rate: 0.5         # Polling rate for position updates in seconds
  enable_polling: true      # Enable/disable position polling

controller:
  address: 1
  protocol: pelco_d
  default_speed: 25
  timeout: 1.0

api:
  host: 127.0.0.1
  port: 8080
  debug: false              # Enable debug mode

client:
  host: 127.0.0.1
  port: 8080
  gui:
    width_scale: 0.6      # Percentage of screen width to use (0.0-1.0)
    height_scale: 0.7     # Percentage of screen height to use (0.0-1.0)
    auto_scale: true      # Whether to automatically scale the GUI
    font_scaling: true    # Whether to scale fonts based on screen resolution
    base_font_size: 10    # Base font size (will be scaled according to resolution)

logging:
  root_level: INFO          # Default log level for unspecified loggers
  file_output: false         # Enable file output for logs
  console_output: true      # Enable console output for logs
  log_dir: logs             # Directory to store log files
  
  # Logger-specific level configuration
  loggers:
    run_all: INFO
    run_all.server_thread: INFO
    run_all.server_thread.serial_tx: INFO
    run_all.server_thread.serial_rx: INFO
    run_all.server_thread.zero_point: INFO
    run_all.server_thread.parser: WARNING
    run_all.client_thread: INFO
    gui_client.api_client: DEBUG
  
  # Pattern-based log level rules - applied if specific logger isn't found
  patterns:
    "*.serial_*": DEBUG     # All serial loggers default to DEBUG
    "*.parser": WARNING     # All parser loggers default to WARNING
    "*": INFO               # Everything else defaults to INFO
