
connection:
  port: COM3            # Use simulator instead of COM port
  baudrate: 9600
  timeout: 1.0
  retries: 3                 
  retry_delay: 0.5
  polling_rate: 0.5         # Polling rate for position updates in seconds
  enable_polling: false      # Enable/disable position polling

controller:
  address: 1
  protocol: pelco_d
  default_speed: 25
  timeout: 1.0

api:
  host: 127.0.0.1
  port: 8080
  debug: false              # Enable debug mode

client:
  host: 127.0.0.1
  port: 8080